name: Copilot Setup Steps

steps:
  - name: Install Rust toolchain
    uses: dtolnay/rust-toolchain@stable
  
  - name: Install R
    uses: r-lib/actions/setup-r@v2
    with:
      r-version: 'release'
      use-public-rspm: true
  
  - name: Install R package dependencies
    uses: r-lib/actions/setup-r-dependencies@v2
    with:
      extra-packages: any::testit, any::roxygen2
      needs: check
