#!/bin/bash
# Script to update vendored Rust dependencies
# This should be run whenever you need to update the Rust crates

set -e

echo "Updating Rust dependencies for tinyimg..."
cd "$(dirname "$0")/src/rust"

echo "Step 1: Removing old vendor directory and archive..."
rm -rf vendor vendor.tar.xz

echo "Step 2: Updating Cargo.lock..."
cargo update

echo "Step 3: Vendoring dependencies (without versioned directories)..."
cargo vendor

echo "Step 4: Note - .cargo/config.toml will be generated by configure script"
# The configure script at package root will create .cargo/config.toml during build

echo "Step 5: Trimming non-essential files from vendored crates..."
find vendor -name ".github" -type d -exec rm -rf {} + 2>/dev/null || true
find vendor -name ".cargo" -type d -exec rm -rf {} + 2>/dev/null || true
find vendor -name ".cargo-checksum.json" -type f -delete 2>/dev/null || true
find vendor -name ".cargo_vcs_info.json" -type f -delete 2>/dev/null || true

# Remove all other hidden files (starting with .)
find vendor -name ".*" -type f -delete 2>/dev/null || true

# Remove CI configuration files
find vendor -name ".gitlab-ci.yml" -type f -delete 2>/dev/null || true
find vendor -name ".travis.yml" -type f -delete 2>/dev/null || true
find vendor -name ".dockerignore" -type f -delete 2>/dev/null || true
find vendor -name ".rustfmt.toml" -type f -delete 2>/dev/null || true
find vendor -name ".editorconfig" -type f -delete 2>/dev/null || true
find vendor -name ".gitignore" -type f -delete 2>/dev/null || true
find vendor -name ".gitattributes" -type f -delete 2>/dev/null || true

# Remove documentation files (keep LICENSE files)
find vendor -name "README*" -type f -delete 2>/dev/null || true
find vendor -name "CHANGELOG*" -type f -delete 2>/dev/null || true
find vendor -name "CONTRIBUTING*" -type f -delete 2>/dev/null || true
find vendor -name "CODE_OF_CONDUCT*" -type f -delete 2>/dev/null || true
find vendor -name "SECURITY*" -type f -delete 2>/dev/null || true
find vendor -name "*.md" -type f ! -name "LICENSE*.md" -delete 2>/dev/null || true

# Remove Cargo.toml.orig files (generated by cargo vendor)
find vendor -name "*.orig" -type f -delete 2>/dev/null || true

# Remove test, benchmark, and example directories
find vendor -name "benches" -type d -exec rm -rf {} + 2>/dev/null || true
find vendor -name "examples" -type d -exec rm -rf {} + 2>/dev/null || true
find vendor -name "tests" -type d -exec rm -rf {} + 2>/dev/null || true

# Remove programs directory from libdeflate (contains test utilities with abort() calls)
rm -rf vendor/libdeflate-sys/libdeflate/programs 2>/dev/null || true

# Remove build scripts for dependencies (we keep build.rs at top level)
find vendor -depth -mindepth 2 -name "build.rs" -type f -delete 2>/dev/null || true

# Remove unnecessary Windows lib files (following gifski's approach)
rm -rf vendor/windows_x86_64_gnullvm/lib/* 2>/dev/null || true
rm -rf vendor/windows_*_msvc/lib/* 2>/dev/null || true
rm -rf vendor/windows_i686*/lib/* 2>/dev/null || true
rm -rf vendor/winapi-i686-pc-windows-gnu/lib/* 2>/dev/null || true

echo "Step 6: Applying patches to remove abort() calls from libdeflate..."
# Apply patches to remove abort() calls which cause R CMD check warnings
if [ -f "vendor/libdeflate-sys/libdeflate/lib/utils.c" ]; then
  cd vendor/libdeflate-sys/libdeflate/lib
  patch -p0 < ../../../../../../patches/utils.c.patch
  patch -p0 < ../../../../../../patches/cpu_features_common.h.patch
  cd ../../../../..
  echo "✓ Patches applied successfully to libdeflate"
else
  echo "⚠ Warning: libdeflate files not found, skipping patches"
fi

echo "Step 7: Creating compressed vendor.tar.xz archive..."
XZ_OPT=-9 tar -cJf vendor.tar.xz vendor/
echo "✓ Created vendor.tar.xz ($(du -h vendor.tar.xz | cut -f1))"

echo ""
echo "✓ Dependencies updated and packaged successfully!"
echo ""
echo "Summary:"
echo "  - vendor/ directory: $(du -sh vendor | cut -f1) (for development)"
echo "  - vendor.tar.xz: $(du -h vendor.tar.xz | cut -f1) (for CRAN releases)"
echo ""
echo "Note: vendor/ is gitignored. Only vendor.tar.xz should be included in"
echo "      CRAN releases (add to .Rbuildignore with ^src/rust/vendor$ pattern)."
echo "      The Makevars will extract it automatically during build."
echo ""
echo "For development: Keep vendor/ directory for cargo builds"
echo "For releases: Include vendor.tar.xz in the package tarball"
echo ""
