#!/bin/bash
# Script to vendor Rust dependencies
# This creates the vendor/ directory needed for development and CRAN releases

set -e

echo "Vendoring Rust dependencies for tinyimg..."

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "Step 1: Removing old vendor directory and archive..."
rm -rf vendor vendor.tar.xz

echo "Step 2: Vendoring dependencies..."
cargo vendor

echo "Step 3: Note - .cargo/config.toml will be generated by configure script"
# The configure script at package root will create .cargo/config.toml during build

# Measure original size
VENDOR_SIZE_ORIG=$(du -sb vendor | cut -f1)
VENDOR_SIZE_ORIG_H=$(du -sh vendor | cut -f1)
FILE_COUNT_ORIG=$(find vendor -type f | wc -l)

echo ""
echo "Step 4: Trimming non-essential files from vendored crates..."
echo "Original vendor/ size: $VENDOR_SIZE_ORIG_H ($FILE_COUNT_ORIG files)"

# Remove .github directories (CI workflows, issue templates)
find vendor -name ".github" -type d -prune -exec rm -rf {} + 2>/dev/null || true

# Remove CI configuration files
find vendor -name ".gitlab-ci.yml" -type f -delete 2>/dev/null || true
find vendor -name ".travis.yml" -type f -delete 2>/dev/null || true
find vendor -name ".dockerignore" -type f -delete 2>/dev/null || true

# Remove documentation files (but keep LICENSE* and README* as they may be referenced)
find vendor -name "CHANGELOG*" -type f -delete 2>/dev/null || true
find vendor -name "CONTRIBUTING*" -type f -delete 2>/dev/null || true
find vendor -name "CODE_OF_CONDUCT*" -type f -delete 2>/dev/null || true
find vendor -name "SECURITY*" -type f -delete 2>/dev/null || true

# Remove test, benchmark, and example directories
find vendor -name "tests" -type d -prune -exec rm -rf {} + 2>/dev/null || true
find vendor -name "benches" -type d -prune -exec rm -rf {} + 2>/dev/null || true
find vendor -name "examples" -type d -prune -exec rm -rf {} + 2>/dev/null || true

# Remove unnecessary Windows lib files (following gifski's approach)
find vendor -type d -name "windows_x86_64_gnullvm" -exec rm -rf {}/lib/* \; 2>/dev/null || true
find vendor -type d -name "windows_*_msvc" -exec rm -rf {}/lib/* \; 2>/dev/null || true
find vendor -type d -name "windows_i686*" -exec rm -rf {}/lib/* \; 2>/dev/null || true

# Measure trimmed size
VENDOR_SIZE_TRIM=$(du -sb vendor | cut -f1)
VENDOR_SIZE_TRIM_H=$(du -sh vendor | cut -f1)
FILE_COUNT_TRIM=$(find vendor -type f | wc -l)

# Calculate savings
SAVED_BYTES=$((VENDOR_SIZE_ORIG - VENDOR_SIZE_TRIM))
SAVED_MB=$((SAVED_BYTES / 1048576))
SAVED_PERCENT=$((SAVED_BYTES * 100 / VENDOR_SIZE_ORIG))
FILES_REMOVED=$((FILE_COUNT_ORIG - FILE_COUNT_TRIM))

echo "Trimmed vendor/ size:  $VENDOR_SIZE_TRIM_H ($FILE_COUNT_TRIM files)"
echo "Space saved: ${SAVED_MB}MB (${SAVED_PERCENT}%) | Files removed: $FILES_REMOVED"

echo ""
echo "Step 5: Regenerating checksums after trimming..."
if [ -f "$SCRIPT_DIR/regenerate-checksums.sh" ]; then
    "$SCRIPT_DIR/regenerate-checksums.sh" vendor
else
    echo "Warning: regenerate-checksums.sh not found, skipping checksum regeneration"
    echo "         This may cause cargo build failures!"
fi

echo ""
echo "Step 6: Creating compressed vendor.tar.xz archive..."
XZ_OPT=-9 tar -cJf vendor.tar.xz vendor/
TAR_SIZE=$(du -b vendor.tar.xz | cut -f1)
TAR_SIZE_H=$(du -h vendor.tar.xz | cut -f1)
TAR_SIZE_KB=$((TAR_SIZE / 1024))

echo "Created vendor.tar.xz: $TAR_SIZE_H (${TAR_SIZE_KB}KB)"

echo ""
echo "========================================"
echo "Vendor Trimming Summary"
echo "========================================"
echo ""
echo "Before trimming:"
echo "  Raw:        $VENDOR_SIZE_ORIG_H ($FILE_COUNT_ORIG files)"
echo ""
echo "After trimming:"
echo "  Raw:        $VENDOR_SIZE_TRIM_H ($FILE_COUNT_TRIM files)"
echo "  Compressed: $TAR_SIZE_H (${TAR_SIZE_KB}KB)"
echo ""
echo "Savings:"
echo "  Raw:        ${SAVED_MB}MB (${SAVED_PERCENT}%)"
echo "  Files:      $FILES_REMOVED removed"
echo ""
echo "========================================"
echo ""
echo "Note: vendor/ is gitignored. Only vendor.tar.xz should be included in"
echo "      CRAN releases (add to .Rbuildignore with ^src/rust/vendor$ pattern)."
echo "      The Makevars will extract it automatically during build."
echo ""
echo "For development: Keep vendor/ directory for cargo builds"
echo "For releases: Include vendor.tar.xz in the package tarball"
echo ""
