#!/bin/bash
# Script to vendor Rust dependencies
# This creates the vendor/ directory needed for development and CRAN releases

set -e

echo "Vendoring Rust dependencies for tinyimg..."

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "Step 1: Removing old vendor directory and archive..."
rm -rf vendor vendor.tar.xz

echo "Step 2: Vendoring dependencies..."
cargo vendor

echo "Step 3: Note - .cargo/config.toml will be generated by configure script"
# The configure script at package root will create .cargo/config.toml during build

echo "Step 4: Creating compressed vendor.tar.xz archive..."
XZ_OPT=-9 tar -cJf vendor.tar.xz vendor/
echo "✓ Created vendor.tar.xz ($(du -h vendor.tar.xz | cut -f1))"

echo ""
echo "✓ Dependencies vendored and packaged successfully!"
echo ""
echo "Summary:"
echo "  - vendor/ directory: $(du -sh vendor | cut -f1) (for development)"
echo "  - vendor.tar.xz: $(du -h vendor.tar.xz | cut -f1) (for CRAN releases)"
echo ""
echo "Note: vendor/ is gitignored. Only vendor.tar.xz should be included in"
echo "      CRAN releases (add to .Rbuildignore with ^src/rust/vendor$ pattern)."
echo "      The Makevars will extract it automatically during build."
echo ""
echo "For development: Keep vendor/ directory for cargo builds"
echo "For releases: Include vendor.tar.xz in the package tarball"
echo ""
