#!/bin/bash
# Script to vendor Rust dependencies
# This creates the vendor/ directory needed for development and CRAN releases

set -e

# Constants
MB=1048576  # Bytes in a megabyte

echo "Vendoring Rust dependencies for tinyimg..."

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "Step 1: Removing old vendor directory and archive..."
rm -rf vendor vendor.tar.xz

echo "Step 2: Vendoring dependencies..."
cargo vendor

echo "Step 3: Note - .cargo/config.toml will be generated by configure script"
# The configure script at package root will create .cargo/config.toml during build

# Measure original size (cross-platform compatible)
# Use -sk for macOS compatibility (instead of GNU-specific -sb)
VENDOR_SIZE_ORIG_KB=$(du -sk vendor | cut -f1)
VENDOR_SIZE_ORIG=$((VENDOR_SIZE_ORIG_KB * 1024))
VENDOR_SIZE_ORIG_H=$(du -sh vendor | cut -f1)
FILE_COUNT_ORIG=$(find vendor -type f | wc -l)

echo ""
echo "Step 4: Trimming non-essential files from vendored crates..."
echo "Original vendor/ size: $VENDOR_SIZE_ORIG_H ($FILE_COUNT_ORIG files)"

# Remove doc include_str lines from Rust source files
# These include external documentation that's not needed for an R package
echo "Removing #[doc = include_str!(...)] lines from vendored .rs files..."
# Use perl for cross-platform compatibility (works on both Linux and macOS)
# Perl's -i flag works consistently across platforms
find vendor -name "*.rs" -type f -exec perl -i -pe 's/^[\s\t]*#!?\[doc\s*=\s*include_str!.*$//g' {} \;

# Remove .github directories (CI workflows, issue templates)
find vendor -name ".github" -type d -prune -exec rm -rf {} +

# Remove CI configuration files
find vendor -name ".gitlab-ci.yml" -type f -delete
find vendor -name ".travis.yml" -type f -delete
find vendor -name ".dockerignore" -type f -delete
find vendor -name ".cirrus.yml" -type f -delete
find vendor -name "*.ps1" -type f -delete

# Remove documentation files (case-insensitive to catch e.g. changelog.md)
find vendor -iname "changelog*" -type f -delete
find vendor -iname "contributing*" -type f -delete
find vendor -iname "contributors*" -type f -delete
find vendor -iname "code_of_conduct*" -type f -delete
find vendor -iname "code-of-conduct*" -type f -delete
find vendor -iname "security*" -type f -delete
find vendor -iname "news*" -type f -delete
find vendor -iname "manual*" -type f -delete
find vendor -iname "releases*" -type f -delete
find vendor -iname "maintainers*" -type f -delete
find vendor -iname "spec.md" -type f -delete
find vendor -iname "nonapi.txt" -type f -delete

# Remove cmake and pkg-config build system files (not used by Rust/cc builds)
find vendor -name "CMakeLists.txt" -type f -delete
find vendor -name "*.cmake.in" -type f -delete
find vendor -name "*.pc.in" -type f -delete
find vendor -name "*.h.in" -type f -delete

# Remove all README files (doc include_str lines already removed above)
find vendor -iname "readme*" -type f -delete

# Remove test, benchmark, example, and scripts directories
find vendor -name "tests" -type d -prune -exec rm -rf {} +
find vendor -name "benches" -type d -prune -exec rm -rf {} +
find vendor -name "examples" -type d -prune -exec rm -rf {} +
find vendor -name "scripts" -type d -prune -exec rm -rf {} +

# Remove all doc directories (doc include_str lines already removed above)
find vendor -name "doc" -type d -prune -exec rm -rf {} +

# Remove development tool configuration files
find vendor -name "Cargo.toml.orig" -type f -delete
find vendor -name "Cargo.lock" -type f -delete
find vendor -name ".cargo_vcs_info.json" -type f -delete
find vendor -name "clippy.toml" -type f -delete
find vendor -name ".rustfmt.toml" -type f -delete
find vendor -name "rustfmt.toml" -type f -delete
find vendor -name "rust-toolchain.toml" -type f -delete
find vendor -name "bors.toml" -type f -delete
find vendor -name ".release-plz.toml" -type f -delete
find vendor -name "triagebot.toml" -type f -delete
find vendor -name "Cross.toml" -type f -delete
find vendor -name "deny.toml" -type f -delete
find vendor -name ".editorconfig" -type f -delete

# Remove git-related files
find vendor -name ".gitignore" -type f -delete
find vendor -name ".git-blame-ignore-revs" -type f -delete

# Remove .cargo/ directories from individual crates (not needed for vendored sources)
find vendor -maxdepth 2 -name ".cargo" -type d -prune -exec rm -rf {} +

# Remove unnecessary Windows lib files (following gifski's approach)
find vendor -type d -name "windows_x86_64_gnullvm" -exec rm -rf {}/lib/* \;
find vendor -type d -name "windows_*_msvc" -exec rm -rf {}/lib/* \;
find vendor -type d -name "windows_i686*" -exec rm -rf {}/lib/* \;

# Fix cargo checksums after removing/modifying files
# When we remove or modify files, the .cargo-checksum.json files need to be updated
# to remove references to deleted files and recalculate hashes for modified files
echo "Fixing cargo checksums after trimming..."
find vendor -name ".cargo-checksum.json" -type f | while read -r checksum_file; do
  # For each checksum file, remove entries for deleted files and recalculate for modified files
  # We use a temporary Python script for this because JSON manipulation is complex in shell
  python3 -c "
import json
import os
import sys
import hashlib

checksum_path = '$checksum_file'
crate_dir = os.path.dirname(checksum_path)

with open(checksum_path, 'r') as f:
    data = json.load(f)

# Update files dict: keep only existing files and recalculate their checksums
if 'files' in data:
    original_count = len(data['files'])
    new_files = {}
    removed_count = 0
    updated_count = 0
    
    for path, old_hash in data['files'].items():
        file_path = os.path.join(crate_dir, path)
        if os.path.exists(file_path):
            # Calculate current checksum
            with open(file_path, 'rb') as f:
                content = f.read()
                new_hash = hashlib.sha256(content).hexdigest()
            new_files[path] = new_hash
            if new_hash != old_hash:
                updated_count += 1
        else:
            removed_count += 1
    
    data['files'] = new_files
    
    if removed_count > 0 or updated_count > 0:
        msg = f'  {os.path.basename(crate_dir)}:'
        if removed_count > 0:
            msg += f' removed {removed_count} entries'
        if updated_count > 0:
            if removed_count > 0:
                msg += ','
            msg += f' updated {updated_count} checksums'
        print(msg, file=sys.stderr)

with open(checksum_path, 'w') as f:
    json.dump(data, f)
" 2>&1
done

# Measure trimmed size (cross-platform compatible)
VENDOR_SIZE_TRIM_KB=$(du -sk vendor | cut -f1)
VENDOR_SIZE_TRIM=$((VENDOR_SIZE_TRIM_KB * 1024))
VENDOR_SIZE_TRIM_H=$(du -sh vendor | cut -f1)
FILE_COUNT_TRIM=$(find vendor -type f | wc -l)

# Calculate savings
SAVED_BYTES=$((VENDOR_SIZE_ORIG - VENDOR_SIZE_TRIM))
SAVED_MB=$((SAVED_BYTES / MB))
SAVED_PERCENT=$((SAVED_BYTES * 100 / VENDOR_SIZE_ORIG))
FILES_REMOVED=$((FILE_COUNT_ORIG - FILE_COUNT_TRIM))

echo "Trimmed vendor/ size:  $VENDOR_SIZE_TRIM_H ($FILE_COUNT_TRIM files)"
echo "Space saved: ${SAVED_MB}MB (${SAVED_PERCENT}%) | Files removed: $FILES_REMOVED"

echo ""
echo "Step 5: Creating compressed vendor.tar.xz archive..."
XZ_OPT=-9 tar -cJf vendor.tar.xz vendor/
TAR_SIZE_KB=$(du -k vendor.tar.xz | cut -f1)
TAR_SIZE=$((TAR_SIZE_KB * 1024))
TAR_SIZE_H=$(du -h vendor.tar.xz | cut -f1)

echo "Created vendor.tar.xz: $TAR_SIZE_H (${TAR_SIZE_KB}KB)"

echo ""
echo "========================================"
echo "Vendor Trimming Summary"
echo "========================================"
echo ""
echo "Before trimming:"
echo "  Raw:        $VENDOR_SIZE_ORIG_H ($FILE_COUNT_ORIG files)"
echo ""
echo "After trimming:"
echo "  Raw:        $VENDOR_SIZE_TRIM_H ($FILE_COUNT_TRIM files)"
echo "  Compressed: $TAR_SIZE_H (${TAR_SIZE_KB}KB)"
echo ""
echo "Savings:"
echo "  Raw:        ${SAVED_MB}MB (${SAVED_PERCENT}%)"
echo "  Files:      $FILES_REMOVED removed"
echo ""
echo "========================================"
echo ""

echo "Step 6: Generating AUTHORS file from dependency crates..."
# Navigate to package root (two directories up from src/rust)
PACKAGE_ROOT="$SCRIPT_DIR/../.."
mkdir -p "$PACKAGE_ROOT/inst"

# Generate AUTHORS file from Cargo.toml metadata
{
  echo "Authors of Rust Crates Included in tinyimg"
  echo "==========================================="
  echo ""
  echo "This file lists the authors of the Rust crates vendored in this package."
  echo ""
  
  # Find all Cargo.toml files in vendor and extract crate name and authors
  find vendor -name "Cargo.toml" -type f | sort | while read -r toml; do
    # Extract crate name
    crate=$(grep '^name = ' "$toml" | head -1 | sed 's/^name = "\(.*\)"/\1/')
    # Extract authors array
    authors=$(grep '^authors = ' "$toml" | head -1 | sed 's/^authors = \[//' | sed 's/\]$//' | tr -d '"')
    if [ -n "$authors" ]; then
      # Process each author (comma-separated)
      echo "$authors" | tr ',' '\n' | while IFS= read -r author; do
        author=$(echo "$author" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        if [ -n "$author" ]; then
          echo "- $crate: $author"
        fi
      done
    fi
  done
} > "$PACKAGE_ROOT/inst/AUTHORS"

echo "Created inst/AUTHORS with author information from vendored crates"

echo ""
echo "Note: vendor/ is gitignored. Only vendor.tar.xz should be included in"
echo "      CRAN releases (add to .Rbuildignore with ^src/rust/vendor$ pattern)."
echo "      The Makevars will extract it automatically during build."
echo ""
echo "For development: Keep vendor/ directory for cargo builds"
echo "For releases: Include vendor.tar.xz in the package tarball"
echo ""
