# Generated by extendr for optimg

optim_png_impl = function(input, output, level, strip, alpha, interlace, fast, preserve, timeout) {
    .Call(wrap__optim_png_impl, input, output, level, strip, alpha, interlace, fast, preserve, timeout)
}
