# Generated by extendr for optimg

optim_png_impl = function(input, output, level, alpha, preserve, verbose, lossy, auto_lossy) {
    .Call(wrap__optim_png_impl, input, output, level, alpha, preserve, verbose, lossy, auto_lossy)
}
